### ISSUE TITLE
Update package.json 

### ISSUE THREAD

**Issue by abrahamcuenca** [Boka44/bakhuLambda#1]
Hi @Boka44 

I was checking out the code for this project. Looks pretty good. You may want to update your package.json file to reflect the project though. If it isn't meant to be open source I would set the license to `"UNLICENSED"` and the `"private": true` to prevent accidental publication

see: https://docs.npmjs.com/files/package.json for more info

https://github.com/Boka44/bakhuLambda/blob/29760d7716a699e6984a8a7f570670101c18bd85/package.json#L2

**Comment by Boka44** [comment]
Thanks Abe! Just updated and merged the PR.
